const API="https://api.github.com", PUBLISHED="content/site.json", DRAFT="content/draft.json";
const state={owner:"",repo:"",branch:"main",token:"",content:null};
const loginPanel=document.querySelector("#login-panel"),editorPanel=document.querySelector("#editor-panel"),loginStatus=document.querySelector("#login-status"),saveStatus=document.querySelector("#save-status"),uploadStatus=document.querySelector("#upload-status"),contentForm=document.querySelector("#content-form");
const headers=()=>({Accept:"application/vnd.github+json",Authorization:`Bearer ${state.token}`,"X-GitHub-Api-Version":"2022-11-28"});
async function github(path,options={}){const response=await fetch(`${API}${path}`,{...options,headers:{...headers(),...(options.headers||{})}});if(!response.ok){const error=await response.json().catch(()=>({}));const e=new Error(error.message||`Erreur GitHub ${response.status}`);e.status=response.status;throw e;}return response.status===204?{}:response.json();}
const decode=value=>decodeURIComponent(escape(atob(value.replace(/\n/g,""))));
const encode=value=>btoa(unescape(encodeURIComponent(value)));
const repoPath=path=>`/repos/${state.owner}/${state.repo}/contents/${path}`;
async function readFile(path){const file=await github(`${repoPath(path)}?ref=${encodeURIComponent(state.branch)}`);return{data:JSON.parse(decode(file.content)),sha:file.sha};}
async function writeJson(path,data,message){let sha;try{sha=(await github(`${repoPath(path)}?ref=${encodeURIComponent(state.branch)}`)).sha;}catch(e){if(e.status!==404)throw e;}return github(repoPath(path),{method:"PUT",body:JSON.stringify({message,content:encode(JSON.stringify(data,null,2)+"\n"),sha,branch:state.branch})});}
function getValue(object,path){return path.split(".").reduce((value,key)=>value?.[key],object);}
function setValue(object,path,value){const keys=path.split(".");const last=keys.pop();const target=keys.reduce((item,key)=>item[key]??={},object);target[last]=value;}
function collectForm(){contentForm.querySelectorAll("input[name],textarea[name]").forEach(field=>{if(field.type==="checkbox")setValue(state.content,field.name,field.checked);else setValue(state.content,field.name,field.value.trim());});}
function fillForm(){contentForm.querySelectorAll("input[name],textarea[name]").forEach(field=>{const value=getValue(state.content,field.name);if(field.type==="checkbox")field.checked=Boolean(value);else if(value!==undefined)field.value=value;});renderHeroPreview();renderImages();}
async function loadContent(){try{state.content=(await readFile(DRAFT)).data;}catch(e){if(e.status!==404)throw e;state.content=(await readFile(PUBLISHED)).data;}state.content.nl??={};state.content.images??=[];state.content.images.forEach(image=>image.captionNl??=image.caption||"");fillForm();}
function renderHeroPreview(source=state.content?.heroImage){const preview=document.querySelector("#hero-preview-image");if(source){preview.src=`../${source}`;preview.closest("figure").hidden=false;}else preview.closest("figure").hidden=true;}
function renderImages(){const list=document.querySelector("#image-list");list.replaceChildren();state.content.images.forEach((image,index)=>{const figure=document.createElement("figure");figure.className="image-item";const img=document.createElement("img");img.src=`../${image.src}`;img.alt="";const fr=document.createElement("input");fr.value=image.caption||"";fr.placeholder="Légende française";fr.addEventListener("input",()=>image.caption=fr.value);const nl=document.createElement("input");nl.value=image.captionNl||"";nl.placeholder="Nederlandse legende";nl.addEventListener("input",()=>image.captionNl=nl.value);const controls=document.createElement("div");controls.className="image-controls";const up=document.createElement("button");up.type="button";up.textContent="←";up.title="Déplacer avant";up.disabled=index===0;up.onclick=()=>{[state.content.images[index-1],state.content.images[index]]=[state.content.images[index],state.content.images[index-1]];renderImages();};const down=document.createElement("button");down.type="button";down.textContent="→";down.title="Déplacer après";down.disabled=index===state.content.images.length-1;down.onclick=()=>{[state.content.images[index],state.content.images[index+1]]=[state.content.images[index+1],state.content.images[index]];renderImages();};const remove=document.createElement("button");remove.type="button";remove.textContent="Retirer";remove.onclick=()=>{state.content.images.splice(index,1);renderImages();};controls.append(up,down,remove);figure.append(img,fr,nl,controls);list.append(figure);});}
document.querySelector("#login-form").addEventListener("submit",async event=>{event.preventDefault();const form=event.currentTarget,fd=new FormData(form);loginStatus.textContent="Connexion…";Object.assign(state,{owner:fd.get("owner").trim(),repo:fd.get("repo").trim(),token:fd.get("token").trim(),branch:fd.get("branch").trim()||"main"});try{const repo=await github(`/repos/${state.owner}/${state.repo}`);if(!repo.permissions?.push)throw new Error("Ce jeton ne permet pas de modifier le dépôt.");await loadContent();form.reset();loginPanel.hidden=true;editorPanel.hidden=false;loginStatus.textContent="";}catch(error){state.token="";loginStatus.textContent=`Connexion refusée : ${error.message}`;}});
async function uploadAsset(file,prefix){if(!/^image\/(jpeg|png|webp)$/.test(file.type))throw new Error(`Format non accepté : ${file.name}`);if(file.size>8*1024*1024)throw new Error(`${file.name} dépasse 8 Mo.`);const ext=file.name.split(".").pop().toLowerCase();const slug=file.name.replace(/\.[^.]+$/," ").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");const path=`assets/uploads/${Date.now()}-${prefix}-${slug||"image"}.${ext}`;const bytes=new Uint8Array(await file.arrayBuffer());let binary="";bytes.forEach(byte=>binary+=String.fromCharCode(byte));await github(repoPath(path),{method:"PUT",body:JSON.stringify({message:`Téléverse ${file.name}`,content:btoa(binary),branch:state.branch})});return path;}
document.querySelector("#hero-file").addEventListener("change",async event=>{const file=event.target.files[0];if(!file)return;uploadStatus.textContent="Téléversement de la photo d’accueil…";try{state.content.heroImage=await uploadAsset(file,"accueil");renderHeroPreview();uploadStatus.textContent="Photo d’accueil téléversée. Enregistrez le brouillon.";}catch(e){uploadStatus.textContent=`Échec : ${e.message}`;}event.target.value="";});
document.querySelector("#image-files").addEventListener("change",async event=>{const files=[...event.target.files];for(let i=0;i<files.length;i++){uploadStatus.textContent=`Téléversement ${i+1}/${files.length}…`;try{const src=await uploadAsset(files[i],"oeuvre");const caption=files[i].name.replace(/\.[^.]+$/,"");state.content.images.push({src,alt:`Œuvre — ${caption}`,caption,captionNl:caption});renderImages();}catch(e){uploadStatus.textContent=`Échec : ${e.message}`;event.target.value="";return;}}uploadStatus.textContent="Photos téléversées. Modifiez les légendes puis enregistrez.";event.target.value="";});
async function saveDraft(){collectForm();await writeJson(DRAFT,state.content,"Enregistre le brouillon du site");saveStatus.textContent="Brouillon enregistré.";}
async function cleanupUnused(){let files=[];try{files=await github(`${repoPath("assets/uploads")}?ref=${encodeURIComponent(state.branch)}`);}catch(e){if(e.status===404)return;throw e;}const used=new Set([state.content.heroImage,...state.content.images.map(image=>image.src)]);for(const file of files)if(file.type==="file"&&!used.has(file.path))await github(repoPath(file.path),{method:"DELETE",body:JSON.stringify({message:`Supprime l’image inutilisée ${file.name}`,sha:file.sha,branch:state.branch})});}
async function busy(button,task){const buttons=document.querySelectorAll(".actions-bar button");buttons.forEach(b=>b.disabled=true);try{await task();}catch(e){saveStatus.textContent=`Échec : ${e.message}`;}finally{buttons.forEach(b=>b.disabled=false);}}
document.querySelector("#save-button").onclick=event=>busy(event.currentTarget,saveDraft);
document.querySelector("#publish-button").onclick=event=>busy(event.currentTarget,async()=>{collectForm();saveStatus.textContent="Publication…";await writeJson(DRAFT,state.content,"Enregistre le brouillon avant publication");await writeJson(PUBLISHED,state.content,"Publie le site bilingue");saveStatus.textContent="Nettoyage des images inutilisées…";await cleanupUnused();saveStatus.textContent="Site publié. La mise à jour sera visible dans quelques instants.";});
document.querySelector("#logout").onclick=()=>{Object.assign(state,{token:"",content:null});contentForm.reset();editorPanel.hidden=true;loginPanel.hidden=false;loginStatus.textContent="Session fermée.";};
